env:
  global:
  # CI_USER_TOKEN={token}
  - secure: RSqYn5LantFyIMOHDiMzylSeRb/yPyJaBARBKWhiQjXawIE+5oTshYEKYYzVZMP6t7wfmqciedM76lQ2JXJV5aGTTeHQN7ULxUpmjq48KQXlecIPwvXV2O4Qe12+RoYKU51Vr8xVBaJQq6L2xH55VCIDsiC1UKD2Jskxvv67J0uIc2GZuzDt/TqTD5ZXnScdN+B8v7lj4NzQl+I5SG/jDg//cSbQ5fjbQlXwGBW+mW0uOoHcEBuTK+JzkY6vz4O69HsIMrtGNsRwzzaASjBiXIBBQS7AjV4aDY+ujuuC6fI75iRvtIC9AcpRu+WNjKWIo+GzLucABzM1uWhjvsELzUXyFgFCMhIgmBFXBlT8Wgckdb443imnNTL632dO0WLByxgyUnpw7PRNxtyLrZI/ovc/AbJQlBdyC9fmpMFqC6SObOw+OM52FvRIaNw/k72688CAMHMkQOTmR8rZNj7/REZrcpXcNhV450PUcFJnwJFvPJePMlLjvH/FH4/9jgwKI0GJW+3XE3RZ8kvIgkjLUNlwOqZPhVi5KDRy8r9LU1GpLizE0vfmxNbfr4XqKtm1TdAv4mvCp7CLdUvWPhi2Lp4wtMaCQQT9csQw9kuC/GQT7WJqz0+iIxnT+CI+fMdkuPJyEmTs0RtGEKW+/Ia4gB12ysArOEdNNnXbSb2JzUw=
  # FASTLANE_PASSWORD={password}
  - secure: j9de5vNOqMIohC52pIWfzyDNjkpgqc5725ahpfC1AyB+LTPnJS1rsY2E3Y3HReQyg1mRDrwF2gI080AW37WvNzd4gll28qs5yu6ySc5jUOnls8o5ZIkqEmY7Ma/hAnKw5K9BinqlMjEudtpQsKVsdgEmOfyB4X+bXO1wcXECqPGc6hWJeIxakIFMcBEuFbo4BSE94tVPYR27qyxT+e0Cxt3+MCAlQ6++gCuK07mrNlcYbvOieR6kz3bjF4K4jd1RNtqXUXiWEL03N9gDDY/GSKQZg/xkDRlld9idzTLvsBOndDIL8CtNwrPvjP6HKj74QTQ3nH+//U2Fkx1gG2WXtAWAdWqFwkMZE3jc3/j/kV5dy9anNxzLdC6DDtzZ1BVtptziLqcmwcvuHkpluo11zsvluYw/daHa5NYgM0HlH5A3aTaJ2Lz4S8tjZLpGhK808WmLvyfpII9uISWyCOqXxna+5/IIjYWD1fZNAaY2potJinWe5zVJ9wYzYt1VWYN7D8fOHywLknux2XGUE1wC7QLRO63AxpTRim4j6UkAlyh5RjY8NUTqryO+E3lLjUsyzIOKEnuq9/RLLkyd/Ua+ecVjjGqIzXw/i6RrtpJ/wTsXLcAj30hNBQOmmSKzj/mAHmsreT7oqgqW0/6u9HWLNV4BWPZLRu/ozu1Kc6vE58A=
  # MATCH_PASSWORD={password}
  - secure: VXh9XD8fKZ5/uuxF+2Vj8thBWTptCi1sOp1H7KPN+D69lXK+GxK3FvFeA9hfHCGLuTN4JJ3RL3gDVD4xZVNHs3PZ3UO/03583hGXPvh3pASrnQJqJtiSfgODMcRkmdL4dCAtgtQCVA67YODYny1J58HiRECyhcePTtxY8L7QweamucUcpwWYDt9G2biLXEk1nY2494+izPTmUvuYI4XxYv5sHOIMVSg1tOe1K2wI4IX/KBNzuexdUI8oPzSgSbf9V9xQ8lBHuhQJbUqSPLnIYq/VJcjBN0Rc8rmX8B8k9zOo9LkIXs98HV2rmAYX6PJaw2YqZhVpUHGRpexQ07DJwYilmXuyN425ZjXE6+L/SRNSd9IMtR/kkguAKOaNRXYThbB1zEABXIz5BtYA/ks/mfeoEIbyZrSQlY9PnMgp3oi/E5kuQOKYB53HfWucIsMHZbFaKpqQkJw7m1dBIzp9lMf/Jz7LAlLQNBxwbEwRx+fc833DaOqLyD/rgbXsmWPqYiWiuatNd5Wth0ZF5OcAIlBjReEt5ZCNa53zGUWyQzQunM6YocRfeM/sscBDdD8sZUyBrXcqHzvokI7x3vmWNIS6at/5w78yOqmDf4OWSTROuJcj10WLp2e4hfJsiM8DrRcv02OwifOIppiv7vnfBv7WigwQLQjYq6sRjOLLbHs=
jobs:
  include:
  # - name: 'JS lint, test, i18n, and Codepush'

  #   language: node_js
  #   node_js: '11'

  #   before_install:
  #   # Fix node file watchers issue https://github.com/gatsbyjs/gatsby/issues/11406#issuecomment-458769756
  #   - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

  #   before_script:
  #   - echo "TRAVIS_COMMIT=$TRAVIS_COMMIT" >> ./.env.production
  #   - |
  #     if [ "$TRAVIS_BRANCH" == "master" ]; then
  #       echo "Setting ENVFILE to .env.production"
  #       export ENVFILE=.env.production
  #     else
  #       echo "Setting ENVFILE to .env.staging"
  #       export ENVFILE=.env.staging
  #     fi
  #   script:
  #   - yarn lint
  #   - yarn lint:ts
  #   - yarn prettier:check

  #   cache:
  #   - yarn

  - name: 'iOS Testflight Build'
    if: branch = master and type = push

    language: objective-c
    xcode_workspace: ios/Voke.xcworkspace
    os: osx
    osx_image: xcode11.1

    install:
    - npm install
    - echo -e "machine github.com\n login $CI_USER_TOKEN" >> ~/.netrc
    - (cd ios && bundler install)

    script:
    - (cd ios && fastlane ios beta)
    # - (cd ios && fastlane ios cru_build_app)

    cache:
    - npm
    - cocoapods
    - bundler
    - directories:
      - $HOME/Library/Developer/Xcode/DerivedData

  - name: 'Android Internal Test Build'
    # if: branch = master and type = push
    if: type = push

    language: android
    dist: trusty
    # android:
    #   components:
    #     - tools
    #     - build-tools-28.0.3
    #     - platform-tools
    #     - tools

    #     - android-28

    #     - extra-google-google_play_services

    #   licenses:
    #     - android-sdk-license-.+

    env:
    # GOOGLE_PLAY_UPLOAD_KEY_PASSWORD={password}
    - secure: Bvy6+b6u+avJDACeOBEht5mXUn11GUHk96XMpFQfu47RXTtl398FMYL9phrxJRgsAkHVr0LcmwjJa5AfQupLcnCIIXhaJLyFn+vegzn82XelCvWT26JdXineH1pVIYq6vRS1XFmgvaf/ohRuZQ/epVq563AsRWr/CbNmRMEvo6/oSglYDnSdommKuOngd4VoDMU0dyBB55tnOJkWZlDXZT6ObsskzNUyLNJVjZlPTCIyTY9Tf14Pu0/lksUv+JGCpTUq20M866veUQASjAo3xXFUspJ8lu+P/LR6Gt9NUBh40YwwTlu7NZxLm1fLX29i5md+zU0yuDNAJuY1wrROpT5h1iQRo1K/Ap+m1wFTYQx4y7zj1+Nz2VLgcIbl1V8DFwJ9XwbG3pHDuqkry8vnSf/ieQtmVnwGV2OzSO2jUvLqwKyGaCODwy+fqNv2ABbbc74bZouwQNCRQDjGTWol88QpV/W7dskAJd9U7QctBXA/EpxVgo3b/blZ9awoh7m8C1T0is491r0Pq183eb9ylJeIjPQUgVxZl5ZiWHxaRu1CGjI+LrVdnT2xoWEXc0mgRIdUhzHyZQITzkRpe55rRtbGymQJHdR6hrEKMkI5GEgCmABkopJDFRZIKML7fNki4HLObs/UKgB2ZwqSqDysHFqDt9t8UrEZEDC8+x0J0GE=

    before_install:
    # Fix node file watchers issue https://github.com/gatsbyjs/gatsby/issues/11406#issuecomment-458769756
    - echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
    - rvm install 2.6.5
    - gem install bundler
    # - git fetch --unshallow
    # - openssl aes-256-cbc -pass "pass:$GOOGLE_PLAY_API_FILE_PASSWORD" -in ./android/fastlane/GooglePlayAPI.enc -out ./android/fastlane/GooglePlayAPI.json -d -a
    - curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
    - sudo apt-get install nodejs -y
    # - curl -o- -L https://yarnpkg.com/install.sh | bash
    # - export PATH="$HOME/.yarn/bin:$PATH"

    # Accept Android SDK licenses so Android Gradle plugin can install dependencies.
    - mkdir "$ANDROID_HOME/licenses" || true
    - echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
    - echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$ANDROID_HOME/licenses/android-sdk-license"
    - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" >> "$ANDROID_HOME/licenses/android-sdk-license"

    # - echo yes | sdkmanager "build-tools;28.0.3" # Android platform required by app
    # - echo yes | sdkmanager "build-tools;25.0.3" # Android platform required by some dependency
    # - echo yes | sdkmanager "build-tools;23.0.1" # Android platform required by some dependency
    install:
    - npm install
    - (cd android && bundler install)

    script:
#    - (cd android && fastlane android beta)
    - (cd android && fastlane android cru_build_app)

    before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
    cache:
    - npm
    - bundler
    - directories:
      - $HOME/.android/build-cache
      - $HOME/.gradle/caches/
      - $HOME/.gradle/wrapper/

notifications:
  email: false
