fastlane_version '2.146.1'

before_all do
  ensure_git_branch
  ensure_git_status_clean
  git_pull
  cocoapods(podfile: './ios/Podfile')
end

platform :ios do
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: 'org.cru.voke', type: 'development', readonly: true)
    match(app_identifier: 'org.cru.voke', type: 'appstore', readonly: true)
  end

  desc 'Build the iOS application.'
  private_lane :build do
    certificates
    increment_build_number(xcodeproj: './ios/voke.xcodeproj')
    gym(scheme: 'Voke', workspace: './ios/voke.xcworkspace')
  end

  desc 'Ship to Testflight.'
  lane :beta do
    build
    pilot
    commit_version_bump(message: '[ci skip] Bump iOS build', xcodeproj: './ios/voke.xcodeproj')
    push_to_git_remote
  end
end
