import { Navigation } from 'react-native-navigation';

import LoadingScreen from './containers/LoadingScreen';
import Login from './containers/Login';
import LoginInput from './containers/LoginInput';
import Home from './containers/Home';
import Videos from './containers/Videos';
import Menu from './containers/Menu';
import About from './containers/About';
import Profile from './containers/Profile';
import Acknowledgements from './containers/Acknowledgements';
import Message from './containers/Message';
import VideoDetails from './containers/VideoDetails';
import SelectFriend from './containers/SelectFriend';
import Contacts from './containers/Contacts';
import KickstartersTab from './containers/KickstartersTab';
import VideosTab from './containers/VideosTab';
import SignUpAccount from './containers/SignUpAccount';
import SignUpProfile from './containers/SignUpProfile';
import SignUpNumber from './containers/SignUpNumber';
import SignUpNumberVerify from './containers/SignUpNumberVerify';
import SignUpWelcome from './containers/SignUpWelcome';
import CountrySelect from './containers/CountrySelect';
import ThemeSelect from './containers/ThemeSelect';
import Help from './containers/Help';
import ForgotPassword from './containers/ForgotPassword';
import SignUpFBAccount from './containers/SignUpFBAccount';
import Modal from './containers/Modal';
import AndroidReportModal from './containers/AndroidReportModal';
import ShareModal from './containers/ShareModal';
import Channels from './containers/Channels';


export default function(store, Provider) {
  Navigation.registerComponent('voke.Loading', () => LoadingScreen, store, Provider);
  Navigation.registerComponent('voke.Login', () => Login, store, Provider);
  Navigation.registerComponent('voke.LoginInput', () => LoginInput, store, Provider);
  Navigation.registerComponent('voke.Home', () => Home, store, Provider);
  Navigation.registerComponent('voke.Menu', () => Menu, store, Provider);
  Navigation.registerComponent('voke.Message', () => Message, store, Provider);
  Navigation.registerComponent('voke.About', () => About, store, Provider);
  Navigation.registerComponent('voke.Help', () => Help, store, Provider);
  Navigation.registerComponent('voke.Profile', () => Profile, store, Provider);
  Navigation.registerComponent('voke.Acknowledgements', () => Acknowledgements, store, Provider);
  Navigation.registerComponent('voke.Videos', () => Videos, store, Provider);
  Navigation.registerComponent('voke.VideoDetails', () => VideoDetails, store, Provider);
  Navigation.registerComponent('voke.SelectFriend', () => SelectFriend, store, Provider);
  Navigation.registerComponent('voke.Contacts', () => Contacts, store, Provider);
  Navigation.registerComponent('voke.KickstartersTab', () => KickstartersTab, store, Provider);
  Navigation.registerComponent('voke.VideosTab', () => VideosTab, store, Provider);
  Navigation.registerComponent('voke.SignUpAccount', () => SignUpAccount, store, Provider);
  Navigation.registerComponent('voke.SignUpProfile', () => SignUpProfile, store, Provider);
  Navigation.registerComponent('voke.SignUpNumber', () => SignUpNumber, store, Provider);
  Navigation.registerComponent('voke.SignUpNumberVerify', () => SignUpNumberVerify, store, Provider);
  Navigation.registerComponent('voke.SignUpWelcome', () => SignUpWelcome, store, Provider);
  Navigation.registerComponent('voke.CountrySelect', () => CountrySelect, store, Provider);
  Navigation.registerComponent('voke.ThemeSelect', () => ThemeSelect, store, Provider);
  Navigation.registerComponent('voke.ForgotPassword', () => ForgotPassword, store, Provider);
  Navigation.registerComponent('voke.SignUpFBAccount', () => SignUpFBAccount, store, Provider);
  Navigation.registerComponent('voke.Modal', () => Modal, store, Provider);
  Navigation.registerComponent('voke.AndroidReportModal', () => AndroidReportModal, store, Provider);
  Navigation.registerComponent('voke.ShareModal', () => ShareModal, store, Provider);
  Navigation.registerComponent('voke.Channels', () => Channels, store, Provider);
}
